services:
  proxy:
    image: jwilder/nginx-proxy:latest
    network_mode: 'host'
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # sonarqube:
  #   image: sonarqube:latest
  #   restart: always
  #   environment:
  #     VIRTUAL_HOST: sonarcube.test
  #     VIRTUAL_PORT: 9000
  #   ports:
  #     - "9092:9092"
  #   networks:
  #     - shared

  mongo:
    image: mongo:6.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongo/:/data/db
    networks:
      - shared

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      VIRTUAL_HOST: mongo-express.test
      VIRTUAL_PORT: 8081
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - shared

  postgres:
    image: postgres:15.0-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./storage/database/:/var/lib/postgresql/data
    networks:
      - shared

  adminer:
    build:
      context: ./adminer
    restart: always
    environment:
      VIRTUAL_HOST: adminer.test
      VIRTUAL_PORT: 8080
      COLOR: 80d5f3
      ## for different types of deployment use different colors

      ## red f57171  (for prod)
      ## yellow f5e071 (for testing and staging)
      ## cyan 71f5cc (for development servers)
      ## blue 80d5f3 (for local development)
    networks:
      - shared

networks:
  shared:
